### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BegleitPanzer** [Walkoud/CS2-Auto-Accept#1]
![image](https://github.com/Walkoud/CS2-Auto-Accept/assets/134264166/c6e497c9-60b8-4ad7-bf9a-7b49768ccb8d)

**Comment by Walkoud** [comment]
Hello, what is your Windows?
Do you have Python installed?
Have you checked to see if your antivirus has done anything?

**Comment by Walkoud** [comment]
just redownload the exe
